---
motd: |
  #!/bin/bash
  #
  echo '    ______           __                  '
  echo '   / ____/___ ______/ /_____  _______  __'
  echo '  / /_  / __ `/ ___/ __/ __ \/ ___/ / / /'
  echo ' / __/ / /_/ / /__/ /_/ /_/ / /  / /_/ / '
  echo '/_/    \__,_/\___/\__/\____/_/   \__, /  '
  echo '                                /____/   '

  # get free memory
  IFS=" " read USED FREE TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$4,$2'})
  # get processes
  PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
  PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
  PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
  PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
  # get processors
  PROCESSOR_NAME=`grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1`
  PROCESSOR_COUNT=`grep -ioP 'processor\t:' /proc/cpuinfo | wc -l`

  W="\e[0;39m"
  G="\e[1;32m"
  B="\e[1;34m"

  echo -e "
  ${W}System Info:
  $W  Uptime......: $W`uptime -p`
  $W  Processes...:$W $G$PROCESS_ROOT$W (root), $G$PROCESS_USER$W (user), $G$PROCESS_ALL$W (total)
  $W  CPU.........: $W$PROCESSOR_NAME ($G$PROCESSOR_COUNT$W vCPU)
  $W  Memory......: $G$USED$W used, $G$FREE$W free, $G$TOTAL$W total$W
  $W  Ruby........:$W {{ ruby_version }}"

  # set column width
  COLUMNS=2
  # colors
  green="\e[1;32m"
  red="\e[1;31m"
  blue="\e[1;34m"
  undim="\e[0m"

  services=("apache2" "rabbitmq-server" "redis-server" "netdata")

  service_status=()
  # get status of all services
  for service in "${services[@]}"; do
      service_status+=($(systemctl is-active "$service"))
  done

  out=""
  for i in ${!services[@]}; do
      # color green if service is active, else red
      if [[ "${service_status[$i]}" == "active" ]]; then
          out+="${services[$i]}:,${green}${service_status[$i]}${undim},"
      else
          out+="${services[$i]}:,${red}${service_status[$i]}${undim},"
      fi
      # insert \n every $COLUMNS column
      if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
          out+="\n"
      fi
  done
  out+="\n"

  printf "\nServices:\n"
  printf "$out" | column -ts $',' | sed -e 's/^/  /'
  echo ""
