---
bashrc: |
  # Aliases
  alias ll="ls -alF"
  alias la="ls -A"
  alias l="ls -CF"
  alias app="cd /var/www/vhosts"
  alias apps="cd /var/www/vhosts"
  alias vhosts="cd /etc/apache2/sites-enabled"
  alias motd="run-parts /etc/update-motd.d/"
  alias sauce="source ~/.bashrc && source ~/.profile"
  alias wtf="man"

  # Alert alias
  # Usage: sleep 10; alert
  alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

  # Ignore if not running interactively
  [ -z "$PS1" ] && return

  # History file configs
  HISTCONTROL=ignoreboth
  shopt -s histappend
  HISTSIZE=1000
  HISTFILESIZE=2000

  # Update lines and columns based on window size
  shopt -s checkwinsize

  # lesspip: make less more friendly
  [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

  # Set chroot variable
  if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
      debian_chroot=$(cat /etc/debian_chroot)
  fi

  # Fancy prompt
  case "$TERM" in
      xterm-color) color_prompt=yes;;
  esac
  force_color_prompt=yes
  if [ -n "$force_color_prompt" ]; then
      if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
          color_prompt=yes
      else
          color_prompt=
      fi
  fi
  if [ "$color_prompt" = yes ]; then
      PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@local\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
  else
      PS1='\u@LOCAL.VM \w: '
  fi
  unset color_prompt force_color_prompt

  # Set xterm title to user@host:dir
  case "$TERM" in
  xterm*|rxvt*)
      PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
      ;;
  *)
      ;;
  esac

  # Enable color support for ls and other aliases
  if [ -x /usr/bin/dircolors ]; then
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
  fi

  # Programmable bash completion
  if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
      . /etc/bash_completion
  fi

  # ssh
  eval "$(ssh-agent -s)">/dev/null 2>&1
  ssh-add ~/.ssh/id_rsa>/dev/null 2>&1

  # Path and environment variables
  export RAILS_ENV=development
  export PATH="$PATH:$HOME/.rvm/bin"
